" provide utf8 encoding
:set encoding=utf-8

" this disables netrwhist saving
let g:netrw_dirhistmax = 0

"this sets up solarized color scheme 
syntax enable
set background=dark
colorscheme solarized

" enables loading filetype detection
filetype plugin on
" enables indenting for specific file types
filetype indent plugin on
" enable latex-suite plugin
let g:tex_flavor='latex'


" enables line numbering 
set number

" ignore case unless upper chars in search pattern
set ignorecase smartcase

" grep will always generate a filename
set grepprg=grep\ -nH\ $*

" :setlocal spell spelllang=en_ca

""""""""""
" Latex
""""""""""
"imap ,t autocmd Filetype tex imap

autocmd FileType tex imap ,it \item

autocmd Filetype tex imap ,bit \begin{itemize}<Enter>

autocmd Filetype tex imap ,eit \end{itemize} <Enter>

autocmd Filetype tex imap ,ben \begin{enumerate} <Enter>

"autocmd Filetype tex imap ,een \end{enumerate}

autocmd Filetype tex imap ,cha \chapter*{

autocmd Filetype tex imap ,ncha \chapter{

autocmd Filetype tex imap ,nsec \section{

autocmd Filetype tex imap ,sec \section*{

autocmd Filetype tex imap ,nsub \subsection{

autocmd Filetype tex imap ,sub \subsection*{

autocmd Filetype tex imap ,ssub \subsubsection*{

autocmd Filetype tex imap ,nssub \subsubsection{

autocmd Filetype tex imap ,bol \textbf{

autocmd Filetype tex imap ,ita \textit{

" latex generic completion includes colon as part of keyword
set iskeyword+=:

"spell check for latex only in english/french
autocmd FileType tex setlocal spell spelllang=en_ca,fr

" This is for vim-latexsuite
set runtimepath+=~/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM,vimfiles/after,~/.vim/after



""""""""""""""""""
" C stuff
""""""""""""""""""
" set F3 for compile c with gcc 
map <F3> : call CompileGcc()<CR>
func! CompileGcc()
  exec "w"
  exec "!gcc % -o %<"
endfunc

" set F4 to compile with gcc & run
"map <F4> :call CompileRunGcc()<CR>
"func! CompileRunGcc()
"  exec "w"
"  exec "!gcc % -o %<"
"  exec "! ./%<"
"endfunc
map <F4> :w <CR> :!gcc % && ./a.out <CR>



" These are so that vim loads the templates by default for specified file "

autocmd! BufNewFile * silent! 0r ~/.vim/skel/tmpl.%:e 
 
"fixing of é letter :
"imap <buffer> <leader>it <Plug>Tex_InsertItemOnThisLine
"imap <C-b> <Plug>Tex_MathBF
"imap <C-c> <Plug>Tex_MathCal
"imap <C-l> <Plug>Tex_LeftRight


"""""""""""""""""""""
" Python
""""""""""""""""""""'
"autocmd FileType * set tabstop=2|set shiftwidth=2|set noexpandtab
"autocmd FileType python set tabstop=4|set shiftwidth=4|set expandtab
""set softtabstop=4 " makes the spaces feel like real tabs
""set modeline

" mystery option for mutt
"setlocal fo+=aw
