#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#-----------------
# Aliases
#----------------

# Directory listing/navigation
alias l='ls --color=auto'  # colors output 
alias la='ls --color=auto -liha | less'  # colors output and gives extra deetz
alias PS1='[\u@\h \W]\$ '
alias ..='cd ..'
alias rmd='rm -r'
alias cpd='cp -r'
#alias pwd='echo "current:" && pwd && echo "actual:" && pwd -P'
alias duh='sudo du -ha --max-depth 1 | sort -h'
alias duhl='du -ha --max-depth 1 | sort -h | less'
alias lsblk='lsblk -o NAME,MAJ:MIN,RM,SIZE,RO,TYPE,FSTYPE,MOUNTPOINT,UUID'
alias xel='grep EE /home/aidan/.local/share/xorg/Xorg.0.log'
alias xl='less /home/aidan/.local/share/xorg/Xorg.0.log'

# pacman shorthands
alias aurget='yaourt'
alias get='sudo pacman -S --needed'
alias up='sudo pacman -Syu; yaourt -Syua; sudo paccache -r -k 3'
alias remove='sudo pacman -R'
alias aids='echo aidan'
alias install='sudo pacman -U'

# editing shortcuts
alias .bash='vim /home/aidan/.bashrc'
alias xmo='vim /home/aidan/.xmonad/xmonad.hs'
 
# shutdown/reboot/etc.
alias shut='systemctl poweroff'
alias reboot='systemctl reboot'

# setsid commonly used programs
alias evince='setsid evince'
alias ch='setsid chromium; exit'
alias calc='setsid gnome-calculator; exit'
alias vlc='setsid vlc'
alias geany='setsid geany'
alias fbreader='setsid FBReader'
alias term='setsid urxvt'
alias gedit='setsid gedit'
alias lk='setsid luakit; exit'
alias audacity='setsid audacity; exit'
alias xournal='setsid xournal'
alias mtpaint='setsid mtpaint'
alias lol='DRI_PRIME=1 setsid playonlinux'
alias qt='setsid qutebrowser'
alias g='DRI_PRIME=1'
alias openttd='setsid openttd'


# systemd 
alias status='sudo systemctl status --lines 80 --full' 
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias enable='sudo systemctl enable'
alias disable='sudo systemctl disable'
alias sus='sudo systemctl suspend'

# other stuff
alias time='timedatectl'
alias nu='setsid nuvolaplayer; setsid urxvt; exit'
alias roox='sudo bash /home/aidan/internet/wireless/roo.sh && startx && pulseaudio --start'
# alias roo='sudo bash /home/aidan/internet/wireless/roo.sh'
alias roo='sudo netctl start wlp9s0-RooCorner'
alias tk='sudo netctl start wlp9s0-Teksavvy'
alias eth='sudo bash /home/aidan/internet/ethernet.sh'
alias ethx='sudo bash /home/aidan/internet/ethernet.sh; startx'
alias edux='sudo bash /home/aidan/internet/wireless/edu.sh; startx'
alias uwx='sudo bash /home/aidan/internet/wireless/uw-un.sh; startx'
alias scan='sudo iwlist wlp1s0 scanning | less'
alias transmission='sudo systemctl start transmission; transmission-cli'
alias backup='sudo bash /mnt/external/aidan/backup.sh'
alias ext='sudo mount /dev/sdb1 /mnt/external'
alias ubuntu='sudo mount /dev/sda6 /mnt/ubuntu'
alias startx='cd; startx'
alias pig='ping -c 1 www.google.com'
alias pigs='ping www.google.com'
alias rpigs='ping 216.52.241.254'
alias deluge='setsid deluge'
alias xmind='setsid XMind'
#alias irssi='start xinetd; sleep 10;  irssi'
alias wup='sudo ip link set wlp9s0 up'
alias wd='sudo ip link set wlp9s0 down'
alias mtag='id3v2'

#####
# Git
####
# git auto-complete 
source /usr/share/git/completion/git-completion.bash
alias git='e git'
alias push='e git push -u origin master'
# set vim as default editor
export EDITOR="vim"


# privacy stuff
alias tchro='sudo systemctl start tor; setsid chromium --incognito --proxy-server="socks://localhost:9050"'
alias tlk='sudo systemctl start tor; sleep 5; setsid torify luakit'

# X stuff
alias merge='xrdb -merge ~/.Xresources'
alias dual='bash /home/aidan/linux/arch/graphics/dual.sh'
alias single='bash /home/aidan/linux/arch/graphics/single.sh'
alias sx='tk;startx'

# Sound/music/language/game
alias pu='pulseaudio --start' 
alias pa='setsid pavucontrol'
alias cmus='cd /home/aidan/music; cmus'
alias al='alsamixer'
alias m='setsid urxvt -e alsamixer;cd ~/; cmus'
alias e='LANG="en_CA.UTF-8"'
alias fe='cd /home/aidan/.config/gvbam/; e gvbam fe6.gba'

# flash
alias org='ln -s /home/aidan/flash/flixel/org'

# ssh
alias sj='ssh aidan@192.168.2.39'
alias sx='ssh aidan@192.168.2.34'


#---------------------------
# Flash stuff
#---------------------------

# get flex-sdk binaries in path

export PATH=/home/aidan/aur/flex-sdk/src/bin:$PATH

# add vim to path




# hacks 4 now
alias hack='sudo systemctl stop dhcpcd.service; sudo ip link set wlp9s0 down; sudo netctl start wlp9s0-RooCorner; startx'

alias chrono='cd /home/aidan/media/games/snes/chrono-trigger/; ./snes9x-gtk "Chrono Trigger.smc"'



#---------------------
# Other
#--------------------

#gets rid of Ctrl-q and Ctrl-s mappings that interfere with rtorrent
stty stop undef
stty start undef

#---------------------
# Games
#---------------------

alias metroid='cd /home/aidan/media/games/snes/chrono-trigger/; ./snes9x-gtk super-metroid.smc'
alias terraria='DRI_PRIME=1 /home/aidan/"GOG Games"/Terraria/start.sh'



alias keys="xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'"

# netctl debug
export NETCTL_DEBUG=yes

export MOZ_PLUGIN_PATH="/usr/lib/mozilla/plugins"


. /home/aidan/torch/install/bin/torch-activate


. /home/aidan/torch-cl/install/bin/torch-activate
